server {

	server_name stock.tanya.9farm.com;

	listen [::]:443 ssl;

	ssl_certificate	    ssl.d/tanya.9farm.com.crt;
	ssl_certificate_key ssl.d/tanya.9farm.com.key;

	access_log /log/stock/access.log;
	error_log  /log/stock/error.log;

	root /www/stock/client/dist;

	location = /worker.js  {
		alias /www/stock/client/src/assets/worker.js;
	}

	location = /assets/manifest.json {
		alias /www/stock/client/src/assets/manifest.json;
	}

	location = /assets/favicon.webp {
		alias /www/stock/client/src/assets/favicon.webp;
	}

	location /_metrics {
		proxy_pass http://127.0.0.1:22721;
	}

	location /api {
		client_max_body_size 100M;
		proxy_pass http://127.0.0.1:22721;
	}

	location / {
		index index.html;
	}

	location = /robots.txt  {
		access_log off;
		log_not_found off;
	}

	location = /favicon.ico {
		expires max;
		access_log off;
		log_not_found off;
	}

	location = /favicon.webp {
		expires max;
		access_log off;
		log_not_found off;
	}
}

server {

	server_name stock.tanya.9farm.com;

	listen [::]:80;

	location / {
		return 301 https://$host$request_uri;
	}
}
